{% set name = "pydantic-numpy" %}
{% set version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydantic_numpy-{{ version }}.tar.gz
  sha256: 1911cb07781f017a18a7620157fd19a658d81050c64bd9714ab97eff92c7a321

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.9,<3.13
    - compress-pickle
    - ruamel.yaml >=0.18.5,<0.19.0
    - numpy >=2.0.0
    - pydantic >=2.0.0,<3.0.0
    - semver >=3.0.1,<4.0.0

test:
  imports:
    - pydantic_numpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/caniko/pydantic-numpy
  summary: Pydantic Model integration of the NumPy array
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/caniko/pydantic-numpy

extra:
  recipe-maintainers:
    - caniko
    - apcamargo
